import * as z from 'zod'
import { Origin } from './origin.model'

// prettier-ignore
export const KnownConditions = {
  AskedGabbroAboutRadioTower: [Origin.BASE_GAME, 'Asked Gabbro about his picture in the radio tower'],
  AskedGabbroForHisShip: [Origin.BASE_GAME, 'Asked Gabbro where his ship is'],
  AUTOPILOT_INTO_SUN: [Origin.BASE_GAME, 'Flew into the sun with autopilot'],
  ChertFirstContact: [Origin.BASE_GAME, 'Has talked to Chert'],
  COMPLETED_SHIPLOG_TUTORIAL: [Origin.DLC, 'Listened to Slate explain the Ship Log\'s "Mark on HUD" function'],
  // seems to be legacy, having the ship log entry is enough?
  DB_VESSEL_X1: [Origin.BASE_GAME, 'Found the Nomai Vessel in Dark Bramble'],
  // seems unused
  DESTROYED_TIMELINE_LAST_SAVE: [Origin.BASE_GAME, 'Destroyed the fabric of spacetime in the last loop'],
  EX_ANGLERFISH_NEST: [Origin.BASE_GAME, 'Found the Anglerfish nest'],
  // never set??
  EX_NOMAI_SHUTTLE_FLYING: [Origin.BASE_GAME, 'Has flown a Nomai Shuttle'],
  EX_SUPERNOVA: [Origin.BASE_GAME, 'Witnessed the supernova'],
  FLEW_TO_SS: [Origin.BASE_GAME, 'Got to the Sun Station without warping'],
  FoundGabbroShip: [Origin.BASE_GAME, "Found Gabbro's ship on Giants Deep"],
  FoundMapSatellite: [Origin.DLC, "Found Gabbro's recording at the Deep Space Satellite"],
  FromGiantsDeep: [Origin.BASE_GAME, 'Hal told the Player the statue is from Giants Deep'],
  GabbroExplanationOver: [Origin.BASE_GAME, 'Discussed both the memory statues and the time loop with Gabbro'],
  GABBRO_MERGE_TRIGGERED: [Origin.BASE_GAME, 'Has completed one of the Gabbro intro paths over multiple time loops'],
  GAME_OVER_LAST_SAVE: [Origin.BASE_GAME, 'Got a Game Over screen in the last loop'],
  HAS_AIMED_TRANSLATOR: [Origin.BASE_GAME, 'Has aimed the translator at Nomai writing'],
  HAS_COMPLETED_DREAM_ZONE_2: [Origin.DLC, 'Found the hidden library under the Candlelit Cove'],
  HAS_CONCEALED_FROM_GHOSTS: [Origin.DLC, 'Has concealed their light from an Owlk'],
  HAS_CONCEALED_IN_DREAM: [Origin.DLC, 'Has concealed their light in the simulation'],
  HAS_DOZED_INTO_DREAM_WORLD: [Origin.DLC, 'Has dozed into the simulation'],
  HAS_FOCUSED_IN_DREAM: [Origin.DLC, 'Has focused their light in the simulation'],
  HAS_PLAYER_LOCKED_ON: [Origin.BASE_GAME, 'Has locked onto a target'],
  HAS_PLAYER_LOCKED_ON_MAP: [Origin.BASE_GAME, 'Has locked onto a target on the map'],
  HAS_RETRIEVED_PROBE: [Origin.BASE_GAME, 'Has recalled a Scout'],
  HAS_ROTATED_PROBE_CAMERA: [Origin.BASE_GAME, 'Has rotated the Scout camera'],
  HAS_SEEN_SUN_EXPLODE: [Origin.BASE_GAME, 'Has witnessed the supernova'],
  HAS_TAKEN_HANDHELD_SNAPSHOT: [Origin.BASE_GAME, "Has used the Scout Launcher's Photo Mode"],
  HAS_TAKEN_MIDAIR_SNAPSHOT: [Origin.BASE_GAME, 'Has taken a snapshot with a flying Scout'],
  HAS_USED_JETPACK: [Origin.BASE_GAME, 'Has used the jetpack'],
  HAS_USED_MAP_SHIP: [Origin.BASE_GAME, 'Has opened the map from the ship'],
  HAS_USED_MAP_SUIT: [Origin.BASE_GAME, 'Has opened the map from the suit'],
  HAS_USED_PREFLIGHT_CHECKLIST: [Origin.BASE_GAME, 'TODO'], // has opened?? preflight checklist
  HAS_USED_SHIPLOG: [Origin.BASE_GAME, 'Has opened the Ship Log'],
  HAS_USED_SLIDE_PROJECTOR: [Origin.DLC, 'Has used a slide reel projector'],
  HAS_USED_TRANSLATOR: [Origin.BASE_GAME, 'Has translated Nomai text with the translator'],
  HIDE_TEMPLE_BASEMENT_ENTRIES: [Origin.DLC, 'Found the basement in the Endless Canyon'],
  // seems to be legacy, having the ship log entry is enough?
  IP_RING_WORLD_X1: [Origin.DLC, 'Found and entered the Stranger'],
  KILLED_BY_SUPERNOVA_AND_KNOWS_IT: [Origin.BASE_GAME, 'Witnessed the supernova and completed at least three full time loops'],
  KILLED_IN_GHOST_MATTER: [Origin.BASE_GAME, 'Has died to Ghost Matter'],
  KNOWS_MEDITATION: [Origin.BASE_GAME, 'Learned Meditation from Gabbro'],
  LAUNCH_CODES_GIVEN: [Origin.BASE_GAME, 'Obtained the launch codes from Hornfels'],
  MARK_ON_HUD_TUTORIAL_COMPLETE: [Origin.DLC, 'Used the Ship Log\'s "Mark on HUD" functionality after Slate explained it'],
  MetFeldspar: [Origin.BASE_GAME, 'Has talked to Feldspar'],
  // unused?
  MetGabbro_Loop1: [Origin.BASE_GAME, 'Talked to Gabbro during the first loop'],
  MET_PRISONER: [Origin.DLC, 'Has talked to the Prisoner'],
  MET_RIEBECK: [Origin.BASE_GAME, 'Has talked to Riebeck'],
  MET_SOLANUM: [Origin.BASE_GAME, 'Has talked to Solanum'],
  PLAYER_ENTERED_TIMELOOPCORE: [Origin.BASE_GAME, 'Entered the warp core in the Ash Twin Project'],
  PLAYER_ENTERED_TIMELOOPCORE_MULTIPLE: [Origin.BASE_GAME, 'Entered the warp core in the Ash Twin Project multiple times in a row'],
  PREFLIGHT_CHECKLIST_UNLOCKED: [Origin.BASE_GAME, 'Unlocked the preflight checklist'],
  PROBE_ENTERED_TIMELOOPCORE: [Origin.BASE_GAME, 'Shot a Scout into the warp core in the Ash Twin Project'],
  SayHiToEsker: [Origin.BASE_GAME, 'Has been told by Marl to say hi to Esker'],
  SUIT_BOOSTER_FIRED: [Origin.BASE_GAME, 'Used the Jetpack booster'],
  TALKED_TO_GABBRO: [Origin.BASE_GAME, 'Has talked to Gabbro'],
  THERE_IS_BUT_VOID: [Origin.BASE_GAME, 'Tried to escape the solar system'],
  TM_MOON_CRATER_X1: [Origin.BASE_GAME, "Found Chert's notes about the Attlerock's main crater"],
  ToldGabbroAboutHisShip: [Origin.BASE_GAME, 'Told Gabbro about his ship'],
  TuffTooSick: [Origin.BASE_GAME, 'Made Tuff feel sick'],
  DGARRO_READ_REEL_Prefab_IP_Reel_1_Story_Complete: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
  DGARRO_READ_REEL_Prefab_IP_Reel_2_Story_Complete: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
  DGARRO_READ_REEL_Prefab_IP_Reel_3_Story_Complete: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
  DGARRO_READ_REEL_Prefab_IP_Reel_4_Story_Vision: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
  DGARRO_READ_REEL_Prefab_IP_Reel_5_Story_Vision_NoInterloperNoVessel: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
  DGARRO_READ_REEL_Prefab_IP_Reel_5_Story_Vision_NoInterloper: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
  DGARRO_READ_REEL_Prefab_IP_Reel_5_Story_Vision_NoVessel: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
  DGARRO_READ_REEL_Prefab_IP_Reel_5_Story_Vision_Complete: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
  DGARRO_READ_REEL_Prefab_IP_Reel_1_Story_Burned: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
  DGARRO_READ_REEL_Prefab_IP_Reel_2_Story_Burned: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
  DGARRO_READ_REEL_Prefab_IP_Reel_3_Story_Burned: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
  DGARRO_READ_REEL_Prefab_IP_Reel_4_Story_Burned: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
  DGARRO_READ_REEL_Prefab_IP_Reel_1_Seal: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
  DGARRO_READ_REEL_Prefab_IP_Reel_2_Seal: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
  DGARRO_READ_REEL_Prefab_IP_Reel_3_Seal: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
  DGARRO_READ_REEL_Prefab_IP_Reel_LanternSecret: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
  DGARRO_READ_REEL_Prefab_IP_Reel_DamageReport: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
  DGARRO_READ_REEL_Prefab_IP_Reel_ExperimentWatch: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
  DGARRO_READ_REEL_Prefab_IP_Reel_ExperimentWatch_Burned: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
  DGARRO_READ_REEL_Prefab_IP_Reel_ExperimentFail: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
  DGARRO_READ_REEL_Prefab_IP_Reel_ExperimentSuccess: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
  DGARRO_READ_REEL_Prefab_IP_Reel_PrisonPeephole_Vision: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
  DGARRO_READ_REEL_Prefab_IP_Reel_TowerVision: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
  DGARRO_READ_REEL_Prefab_IP_Reel_Burning: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
  DGARRO_READ_REEL_Prefab_IP_Reel_1_LibraryPath: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
  DGARRO_READ_REEL_Prefab_IP_Reel_2_LibraryPath: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
  DGARRO_READ_REEL_Prefab_IP_Reel_3_LibraryPath: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
  DGARRO_READ_REEL_Prefab_IP_Reel_1_DreamRule: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
  DGARRO_READ_REEL_Prefab_IP_Reel_2_DreamRule_v1: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
  DGARRO_READ_REEL_Prefab_IP_Reel_2_DreamRule_v2: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
  DGARRO_READ_REEL_Prefab_IP_Reel_3_DreamRule: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
  DGARRO_READ_REEL_Prefab_IP_Reel_PrisonerFarewellVision: [Origin.SLIDE_REEL_PLAYER_PLUS, null],
} satisfies Record<string, [Origin, string | null]>
export const KnownConditionKey = z.literal(
  Object.keys(KnownConditions) as (keyof typeof KnownConditions)[],
)
export type KnownConditionKey = z.infer<typeof KnownConditionKey>
export const ConditionKey = z.union([KnownConditionKey, z.string()])
export type ConditionKey = z.infer<typeof ConditionKey>
